services:
  mysql:
    image: 'mysql:latest'
    container_name: db
    environment:
      - 'MYSQL_DATABASE=hkb'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
    volumes:
      - ./:/app/var/lib/mysql
    ports:
      - 3306:3306
